### ISSUE TITLE
API return 402: Payment required

### ISSUE THREAD

**Issue by chenjianxin** [TrainingByPackt/Server-Side-Enterprise-Development-with-Angular#1]
hello,

when I access the apiUrl  https://packt-angular-social.now.sh/
and it return 402: Payment required

**Comment by beeman** [comment]
Hi @chenjianxin,

Thanks for reaching out. This was due to a change I made in my subscription for now.sh.

I have re-deployed the API and it should now work again.

Good luck with the course!!
